### IMPORTING NECESSARY LIBRARIES

In [124]:
import sqlite3
import csv
import pandas as pd
import numpy as np

#### creating cars database

In [129]:
con = sqlite3.connect("cartest.db")
cur = con.cursor()

### IMPORT DATA-SET TO BE USED

In [130]:
data = pd.read_csv('Automobile_miles_per_gallon.csv')
data.head()

    mpg  cyl  displ   hp  weight  accel  yr origin                       name
0  18.0    8  307.0  130    3504   12.0  70     US  chevrolet chevelle malibu
1  15.0    8  350.0  165    3693   11.5  70     US          buick skylark 320
2  18.0    8  318.0  150    3436   11.0  70     US         plymouth satellite
3  16.0    8  304.0  150    3433   12.0  70     US              amc rebel sst
4  17.0    8  302.0  140    3449   10.5  70     US                ford torino

###  CREATING the train and test data set

In [131]:
from sklearn.model_selection import train_test_split
#split the data into train and test set
train,test = train_test_split(data, test_size=0.20, random_state=20)
#save the data
train.to_csv('train.csv',index=False)
test.to_csv('test.csv',index=False)

#### Creating the table

In [132]:
table = """CREATE TABLE autotest
(mpg REAL, cyl INTEGER, displREAL, hp INTEGER,weight INTEGER, accel REAL, yr REAL, Origin TEXT, name TEXT)"""

In [133]:
cur.execute(table)

In [134]:
file = open("test.csv")
rows = csv.reader(file)
cur.executemany("INSERT INTO  autotest VALUES (?, ?, ?, ?, ?, ?, ?, ?, ? )", rows)

#### LET'S QUERY THE DATA SET

 FETCHING THE ENTIRE SET FROM THE DATA SET, using pandas for clearer visiblity

In [135]:
 a = cur.execute("SELECT * FROM autotest")
#print(cur.fetchall())
df = pd.DataFrame(a)
print (df)

       0    1      2    3       4      5   6       7                     8
0    mpg  cyl  displ   hp  weight  accel  yr  origin                  name
1     15    8  383.0  170    3563     10  70      US   dodge challenger se
2   31.9    4   89.0   71    1925     14  79  Europe      vw rabbit custom
3     16    8  400.0  230    4278    9.5  73      US    pontiac grand prix
4   34.5    4  105.0   70    2150   14.9  79      US  plymouth horizon tc3
..   ...  ...    ...  ...     ...    ...  ..     ...                   ...
75    32    4   71.0   65    1836     21  74    Asia   toyota corolla 1200
76    28    4  120.0   79    2625   18.6  82      US           ford ranger
77    29    4  135.0   84    2525     16  82      US        dodge aries se
78     9    8  304.0  193    4732   18.5  70      US              hi 1200d
79    13    8  351.0  158    4363     13  73      US              ford ltd

[80 rows x 9 columns]

#####  LET'S PRINT THE FIRST ROW

In [136]:
cur.execute("SELECT * FROM autotest")
print(cur.fetchone())

('mpg', 'cyl', 'displ', 'hp', 'weight', 'accel', 'yr', 'origin', 'name')

#####  LET'S FETCH 4 ROWS

In [137]:
cur.execute("SELECT * FROM autotest")
b= cur.fetchmany(4)
df = pd.DataFrame(b)

print(df)

      0    1      2    3       4      5   6       7                    8
0   mpg  cyl  displ   hp  weight  accel  yr  origin                 name
1    15    8  383.0  170    3563     10  70      US  dodge challenger se
2  31.9    4   89.0   71    1925     14  79  Europe     vw rabbit custom
3    16    8  400.0  230    4278    9.5  73      US   pontiac grand prix

In [140]:
cur.execute("SELECT * FROM autotest")
items = cur.fetchall()

#### printing all values in the database using for loop

In [159]:
    for x in items:
         print (x)

('mpg', 'cyl', 'displ', 'hp', 'weight', 'accel', 'yr', 'origin', 'name')
(15.0, 8, '383.0', 170, 3563, 10.0, 70.0, 'US', 'dodge challenger se')
(31.9, 4, '89.0', 71, 1925, 14.0, 79.0, 'Europe', 'vw rabbit custom')
(16.0, 8, '400.0', 230, 4278, 9.5, 73.0, 'US', 'pontiac grand prix')
(34.5, 4, '105.0', 70, 2150, 14.9, 79.0, 'US', 'plymouth horizon tc3')
(21.0, 6, '200.0', 85, 2587, 16.0, 70.0, 'US', 'ford maverick')
(34.0, 4, '108.0', 70, 2245, 16.9, 82.0, 'Asia', 'toyota corolla')
(37.0, 4, '85.0', 65, 1975, 19.4, 81.0, 'Asia', 'datsun 210 mpg')
(18.0, 6, '232.0', 100, 2945, 16.0, 73.0, 'US', 'amc hornet')
(43.4, 4, '90.0', 48, 2335, 23.7, 80.0, 'Europe', 'vw dasher (diesel)')
(17.5, 8, '305.0', 140, 4215, 13.0, 76.0, 'US', 'chevrolet chevelle malibu classic')
(22.0, 4, '108.0', 94, 2379, 16.5, 73.0, 'Asia', 'datsun 610')
(14.0, 8, '455.0', 225, 3086, 10.0, 70.0, 'US', 'buick estate wagon (sw)')
(40.8, 4, '85.0', 65, 2110, 19.2, 80.0, 'Asia', 'datsun 210')
(18.6, 6, '225.0', 110, 3620, 18.7, 78.0, 'US', 'dodge aspen')
(13.0, 8, '360.0', 175, 3821, 11.0, 73.0, 'US', 'amc ambassador brougham')
(26.5, 4, '140.0', 72, 2565, 13.6, 76.0, 'US', 'ford pinto')
(18.0, 6, '171.0', 97, 2984, 14.5, 75.0, 'US', 'ford pinto')
(23.0, 4, '120.0', 97, 2506, 14.5, 72.0, 'Asia', 'toyouta corona mark ii (sw)')
(22.0, 6, '146.0', 97, 2815, 14.5, 77.0, 'Asia', 'datsun 810')
(15.0, 8, '390.0', 190, 3850, 8.5, 70.0, 'US', 'amc ambassador dpl')
(12.0, 8, '455.0', 225, 4951, 11.0, 73.0, 'US', 'buick electra 225 custom')
(14.0, 8, '318.0', 150, 4237, 14.5, 73.0, 'US', 'plymouth fury gran sedan')
(17.0, 6, '250.0', 100, 3329, 15.5, 71.0, 'US', 'chevrolet chevelle malibu')
(14.0, 8, '440.0', 215, 4312, 8.5, 70.0, 'US', 'plymouth fury iii')
(15.0, 8, '318.0', 150, 4135, 13.5, 72.0, 'US', 'plymouth fury iii')
(32.4, 4, '108.0', 75, 2350, 16.8, 81.0, 'Asia', 'toyota corolla')
(18.2, 8, '318.0', 135, 3830, 15.2, 79.0, 'US', 'dodge st. regis')
(19.9, 8, '260.0', 110, 3365, 15.5, 78.0, 'US', 'oldsmobile cutlass salon brougham')
(36.0, 4, '107.0', 75, 2205, 14.5, 82.0, 'Asia', 'honda accord')
(13.0, 8, '360.0', 170, 4654, 13.0, 73.0, 'US', 'plymouth custom suburb')
(15.0, 6, '258.0', 110, 3730, 19.0, 75.0, 'US', 'amc matador')
(21.5, 4, '121.0', 110, 2600, 12.8, 77.0, 'Europe', 'bmw 320i')
(18.0, 6, '250.0', 88, 3139, 14.5, 71.0, 'US', 'ford mustang')
(36.0, 4, '79.0', 58, 1825, 18.6, 77.0, 'Europe', 'renault 5 gtl')
(24.0, 4, '113.0', 95, 2278, 15.5, 72.0, 'Asia', 'toyota corona hardtop')
(28.0, 4, '112.0', 88, 2605, 19.6, 82.0, 'US', 'chevrolet cavalier')
(19.0, 6, '225.0', 100, 3630, 17.7, 77.0, 'US', 'plymouth volare custom')
(31.0, 4, '119.0', 82, 2720, 19.4, 82.0, 'US', 'chevy s-10')
(32.3, 4, '97.0', 67, 2065, 17.8, 81.0, 'Asia', 'subaru')
(24.0, 4, '121.0', 110, 2660, 14.0, 73.0, 'Europe', 'saab 99le')
(33.0, 4, '91.0', 53, 1795, 17.5, 75.0, 'Asia', 'honda civic cvcc')
(13.0, 8, '350.0', 165, 4274, 12.0, 72.0, 'US', 'chevrolet impala')
(24.0, 4, '116.0', 75, 2158, 15.5, 73.0, 'Europe', 'opel manta')
(18.0, 3, '70.0', 90, 2124, 13.5, 73.0, 'Asia', 'maxda rx3')
(16.0, 8, '400.0', 180, 4220, 11.1, 77.0, 'US', 'pontiac grand prix lj')
(19.2, 6, '231.0', 105, 3535, 19.2, 78.0, 'US', 'pontiac phoenix lj')
(35.7, 4, '98.0', 80, 1915, 14.4, 79.0, 'US', 'dodge colt hatchback custom')
(28.4, 4, '151.0', 90, 2670, 16.0, 79.0, 'US', 'buick skylark limited')
(24.0, 4, '113.0', 95, 2372, 15.0, 70.0, 'Asia', 'toyota corona mark ii')
(19.1, 6, '225.0', 90, 3381, 18.7, 80.0, 'US', 'dodge aspen')
(16.0, 6, '250.0', 100, 3781, 17.0, 74.0, 'US', 'chevrolet chevelle malibu classic')
(15.5, 8, '350.0', 170, 4165, 11.4, 77.0, 'US', 'chevrolet monte carlo landau')
(22.5, 6, '232.0', 90, 3085, 17.6, 76.0, 'US', 'amc hornet')
(26.0, 4, '122.0', 80, 2451, 16.5, 74.0, 'US', 'ford pinto')
(17.0, 8, '305.0', 130, 3840, 15.4, 79.0, 'US', 'chevrolet caprice classic')
(13.0, 8, '400.0', 150, 4464, 12.0, 73.0, 'US', 'chevrolet caprice classic')
(35.1, 4, '81.0', 60, 1760, 16.1, 81.0, 'Asia', 'honda civic 1300')
(25.0, 4, '116.0', 81, 2220, 16.9, 76.0, 'Europe', 'opel 1900')
(24.0, 4, '120.0', 97, 2489, 15.0, 74.0, 'Asia', 'honda civic')
(19.2, 8, '305.0', 145, 3425, 13.2, 78.0, 'US', 'chevrolet monte carlo landau')
(20.8, 6, '200.0', 85, 3070, 16.7, 78.0, 'US', 'mercury zephyr')
(33.0, 4, '91.0', 53, 1795, 17.4, 76.0, 'Asia', 'honda civic')
(12.0, 8, '429.0', 198, 4952, 11.5, 73.0, 'US', 'mercury marquis brougham')
(15.0, 8, '302.0', 130, 4295, 14.9, 77.0, 'US', 'mercury cougar brougham')
(32.7, 6, '168.0', 132, 2910, 11.4, 80.0, 'Asia', 'datsun 280-zx')
(26.0, 4, '108.0', 93, 2391, 15.5, 74.0, 'Asia', 'subaru')
(16.5, 8, '351.0', 138, 3955, 13.2, 79.0, 'US', 'mercury grand marquis')
(17.7, 6, '231.0', 165, 3445, 13.4, 78.0, 'US', 'buick regal sport coupe (turbo)')
(17.5, 8, '305.0', 145, 3880, 12.5, 77.0, 'US', 'chevrolet caprice classic')
(16.9, 8, '350.0', 155, 4360, 14.9, 79.0, 'US', 'buick estate wagon (sw)')
(24.5, 4, '151.0', 88, 2740, 16.0, 77.0, 'US', 'pontiac sunbird coupe')
(35.0, 4, '122.0', 88, 2500, 15.1, 80.0, 'Europe', 'triumph tr7 coupe')
(27.0, 4, '112.0', 88, 2640, 18.6, 82.0, 'US', 'chevrolet cavalier wagon')
(34.1, 4, '91.0', 68, 1985, 16.0, 81.0, 'Asia', 'mazda glc 4')
(32.0, 4, '71.0', 65, 1836, 21.0, 74.0, 'Asia', 'toyota corolla 1200')
(28.0, 4, '120.0', 79, 2625, 18.6, 82.0, 'US', 'ford ranger')
(29.0, 4, '135.0', 84, 2525, 16.0, 82.0, 'US', 'dodge aries se')
(9.0, 8, '304.0', 193, 4732, 18.5, 70.0, 'US', 'hi 1200d')
(13.0, 8, '351.0', 158, 4363, 13.0, 73.0, 'US', 'ford ltd')

printing only two values from the table int he database

In [117]:
for x in items:
    mpg, cyl, displ, hp, weight, accel, yr, origin, name = x
   
    print (x)

PRINTING only the mpg column

In [21]:
for x in items:
    mpg, _, _, _, _, _, _, _, name = x
    print (mpg)

mpg
18.0
15.0
18.0
16.0
17.0
15.0
14.0
14.0
14.0
15.0
15.0
14.0
15.0
14.0
24.0
22.0
18.0
21.0
27.0
26.0
25.0
24.0
25.0
26.0
21.0
10.0
10.0
11.0
9.0
27.0
28.0
25.0
19.0
16.0
17.0
19.0
18.0
14.0
14.0
14.0
14.0
12.0
13.0
13.0
18.0
22.0
19.0
18.0
23.0
28.0
30.0
30.0
31.0
35.0
27.0
26.0
24.0
25.0
23.0
20.0
21.0
13.0
14.0
15.0
14.0
17.0
11.0
13.0
12.0
13.0
19.0
15.0
13.0
13.0
14.0
18.0
22.0
21.0
26.0
22.0
28.0
23.0
28.0
27.0
13.0
14.0
13.0
14.0
15.0
12.0
13.0
13.0
14.0
13.0
12.0
13.0
18.0
16.0
18.0
18.0
23.0
26.0
11.0
12.0
13.0
12.0
18.0
20.0
21.0
22.0
18.0
19.0
21.0
26.0
15.0
16.0
29.0
24.0
20.0
19.0
15.0
24.0
20.0
11.0
20.0
19.0
15.0
31.0
26.0
32.0
25.0
16.0
16.0
18.0
16.0
13.0
14.0
14.0
14.0
29.0
26.0
26.0
31.0
32.0
28.0
24.0
26.0
24.0
26.0
31.0
19.0
18.0
15.0
15.0
16.0
15.0
16.0
14.0
17.0
16.0
15.0
18.0
21.0
20.0
13.0
29.0
23.0
20.0
23.0
24.0
25.0
24.0
18.0
29.0
19.0
23.0
23.0
22.0
25.0
33.0
28.0
25.0
25.0
26.0
27.0
17.5
16.0
15.5
14.5
22.0
22.0
24.0
22.5
29.0
24.5
29.0
33.0
20.0
18.0
18.5
17.5
29.5
32.0
28.0
26.5
20.0
13.0
19.0
19.0
16.5
16.5
13.0
13.0
13.0
31.5
30.0
36.0
25.5
33.5
17.5
17.0
15.5
15.0
17.5
20.5
19.0
18.5
16.0
15.5
15.5
16.0
29.0
24.5
26.0
25.5
30.5
33.5
30.0
30.5
22.0
21.5
21.5
43.1
36.1
32.8
39.4
36.1
19.9
19.4
20.2
19.2
20.5
20.2
25.1
20.5
19.4
20.6
20.8
18.6
18.1
19.2
17.7
18.1
17.5
30.0
27.5
27.2
30.9
21.1
23.2
23.8
23.9
20.3
17.0
21.6
16.2
31.5
29.5
21.5
19.8
22.3
20.2
20.6
17.0
17.6
16.5
18.2
16.9
15.5
19.2
18.5
31.9
34.1
35.7
27.4
25.4
23.0
27.2
23.9
34.2
34.5
31.8
37.3
28.4
28.8
26.8
33.5
41.5
38.1
32.1
37.2
28.0
26.4
24.3
19.1
34.3
29.8
31.3
37.0
32.2
46.6
27.9
40.8
44.3
43.4
36.4
30.0
44.6
33.8
29.8
32.7
23.7
35.0
32.4
27.2
26.6
25.8
23.5
30.0
39.1
39.0
35.1
32.3
37.0
37.7
34.1
34.7
34.4
29.9
33.0
33.7
32.4
32.9
31.6
28.1
30.7
25.4
24.2
22.4
26.6
20.2
17.6
28.0
27.0
34.0
31.0
29.0
27.0
24.0
36.0
37.0
31.0
38.0
36.0
36.0
36.0
34.0
38.0
32.0
38.0
25.0
38.0
26.0
22.0
32.0
36.0
27.0
27.0
44.0
32.0
28.0
31.0

print origin

In [22]:
for x in items:
    mpg, _, _, _, _, _, _, _, name = x
    print  (_)

origin
US
US
US
US
US
US
US
US
US
US
US
US
US
US
Asia
US
US
US
Asia
Europe
Europe
Europe
Europe
Europe
US
US
US
US
US
Asia
US
Asia
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
Europe
Europe
Europe
Asia
Asia
Europe
US
Asia
US
Europe
US
US
US
US
US
US
US
US
US
US
US
Asia
US
US
US
US
Europe
Europe
Europe
Europe
US
Asia
Asia
US
Asia
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
Europe
US
US
US
US
US
Asia
US
Asia
Asia
US
US
Europe
US
US
Europe
Europe
Europe
Europe
US
Europe
Asia
US
US
US
US
Asia
US
Asia
US
US
US
US
US
US
US
US
US
Europe
Europe
Europe
Asia
Asia
US
Europe
Europe
Asia
Asia
Europe
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
Asia
US
US
US
Asia
Europe
Asia
US
Europe
US
Europe
Europe
Europe
Europe
Asia
Europe
Europe
US
US
Europe
US
US
US
US
US
US
US
US
US
US
Europe
Asia
US
US
US
US
Europe
Asia
Asia
US
Europe
US
Europe
Asia
Europe
US
US
US
US
Asia
US
Europe
US
Asia
US
US
US
US
US
US
US
US
US
US
US
US
Europe
US
Asia
US
US
US
Asia
Europe
Asia
Europe
Asia
Europe
US
Asia
Asia
Asia
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
US
Asia
Asia
US
Asia
US
US
Asia
Europe
Europe
Europe
Europe
Europe
Asia
US
US
US
US
US
US
US
US
US
US
US
US
US
Europe
Asia
US
US
Europe
US
Europe
US
US
US
Asia
Europe
US
US
US
US
Europe
Asia
US
Asia
US
US
US
US
Europe
Asia
Asia
Asia
Asia
Asia
US
Asia
Europe
Europe
Europe
Europe
Asia
Asia
Europe
Asia
Asia
Europe
Asia
US
US
US
US
US
Asia
US
Asia
Asia
Asia
Asia
Asia
US
US
US
Europe
Asia
Asia
Asia
Asia
Europe
Europe
Asia
Asia
US
US
US
US
US
US
US
US
US
US
US
Europe
Asia
Asia
US
US
Asia
Asia
Asia
Asia
Asia
Asia
US
US
US
US
Asia
US
US
US
Europe
US
US
US

printing mpg, accel and name

In [23]:
for x in items:
    mpg, cyl, displ, hp, weight, accel, yr, origin, name = x
    print (f"{mpg}\t\t{accel}\t\t{name}")

mpg		accel		name
18.0		12.0		chevrolet chevelle malibu
15.0		11.5		buick skylark 320
18.0		11.0		plymouth satellite
16.0		12.0		amc rebel sst
17.0		10.5		ford torino
15.0		10.0		ford galaxie 500
14.0		9.0		chevrolet impala
14.0		8.5		plymouth fury iii
14.0		10.0		pontiac catalina
15.0		8.5		amc ambassador dpl
15.0		10.0		dodge challenger se
14.0		8.0		plymouth 'cuda 340
15.0		9.5		chevrolet monte carlo
14.0		10.0		buick estate wagon (sw)
24.0		15.0		toyota corona mark ii
22.0		15.5		plymouth duster
18.0		15.5		amc hornet
21.0		16.0		ford maverick
27.0		14.5		datsun pl510
26.0		20.5		volkswagen 1131 deluxe sedan
25.0		17.5		peugeot 504
24.0		14.5		audi 100 ls
25.0		17.5		saab 99e
26.0		12.5		bmw 2002
21.0		15.0		amc gremlin
10.0		14.0		ford f250
10.0		15.0		chevy c20
11.0		13.5		dodge d200
9.0		18.5		hi 1200d
27.0		14.5		datsun pl510
28.0		15.5		chevrolet vega 2300
25.0		14.0		toyota corona
19.0		13.0		amc gremlin
16.0		15.5		plymouth satellite custom
17.0		15.5		chevrolet chevelle malibu
19.0		15.5		ford torino 500
18.0		15.5		amc matador
14.0		12.0		chevrolet impala
14.0		11.5		pontiac catalina brougham
14.0		13.5		ford galaxie 500
14.0		13.0		plymouth fury iii
12.0		11.5		dodge monaco (sw)
13.0		12.0		ford country squire (sw)
13.0		12.0		pontiac safari (sw)
18.0		13.5		amc hornet sportabout (sw)
22.0		19.0		chevrolet vega (sw)
19.0		15.0		pontiac firebird
18.0		14.5		ford mustang
23.0		14.0		mercury capri 2000
28.0		14.0		opel 1900
30.0		19.5		peugeot 304
30.0		14.5		fiat 124b
31.0		19.0		toyota corolla 1200
35.0		18.0		datsun 1200
27.0		19.0		volkswagen model 111
26.0		20.5		plymouth cricket
24.0		15.5		toyota corona hardtop
25.0		17.0		dodge colt hardtop
23.0		23.5		volkswagen type 3
20.0		19.5		chevrolet vega
21.0		16.5		ford pinto runabout
13.0		12.0		chevrolet impala
14.0		12.0		pontiac catalina
15.0		13.5		plymouth fury iii
14.0		13.0		ford galaxie 500
17.0		11.5		amc ambassador sst
11.0		11.0		mercury marquis
13.0		13.5		buick lesabre custom
12.0		13.5		oldsmobile delta 88 royale
13.0		12.5		chrysler newport royal
19.0		13.5		mazda rx2 coupe
15.0		12.5		amc matador (sw)
13.0		14.0		chevrolet chevelle concours (sw)
13.0		16.0		ford gran torino (sw)
14.0		14.0		plymouth satellite custom (sw)
18.0		14.5		volvo 145e (sw)
22.0		18.0		volkswagen 411 (sw)
21.0		19.5		peugeot 504 (sw)
26.0		18.0		renault 12 (sw)
22.0		16.0		ford pinto (sw)
28.0		17.0		datsun 510 (sw)
23.0		14.5		toyouta corona mark ii (sw)
28.0		15.0		dodge colt (sw)
27.0		16.5		toyota corolla 1600 (sw)
13.0		13.0		buick century 350
14.0		11.5		amc matador
13.0		13.0		chevrolet malibu
14.0		14.5		ford gran torino
15.0		12.5		dodge coronet custom
12.0		11.5		mercury marquis brougham
13.0		12.0		chevrolet caprice classic
13.0		13.0		ford ltd
14.0		14.5		plymouth fury gran sedan
13.0		11.0		chrysler new yorker brougham
12.0		11.0		buick electra 225 custom
13.0		11.0		amc ambassador brougham
18.0		16.5		plymouth valiant
16.0		18.0		chevrolet nova custom
18.0		16.0		amc hornet
18.0		16.5		ford maverick
23.0		16.0		plymouth duster
26.0		21.0		volkswagen super beetle
11.0		14.0		chevrolet impala
12.0		12.5		ford country
13.0		13.0		plymouth custom suburb
12.0		12.5		oldsmobile vista cruiser
18.0		15.0		amc gremlin
20.0		19.0		toyota carina
21.0		19.5		chevrolet vega
22.0		16.5		datsun 610
18.0		13.5		maxda rx3
19.0		18.5		ford pinto
21.0		14.0		mercury capri v6
26.0		15.5		fiat 124 sport coupe
15.0		13.0		chevrolet monte carlo s
16.0		9.5		pontiac grand prix
29.0		19.5		fiat 128
24.0		15.5		opel manta
20.0		14.0		audi 100ls
19.0		15.5		volvo 144ea
15.0		11.0		dodge dart custom
24.0		14.0		saab 99le
20.0		13.5		toyota mark ii
11.0		11.0		oldsmobile omega
20.0		16.5		plymouth duster
19.0		16.0		amc hornet
15.0		17.0		chevrolet nova
31.0		19.0		datsun b210
26.0		16.5		ford pinto
32.0		21.0		toyota corolla 1200
25.0		17.0		chevrolet vega
16.0		17.0		chevrolet chevelle malibu classic
16.0		18.0		amc matador
18.0		16.5		plymouth satellite sebring
16.0		14.0		ford gran torino
13.0		14.5		buick century luxus (sw)
14.0		13.5		dodge coronet custom (sw)
14.0		16.0		ford gran torino (sw)
14.0		15.5		amc matador (sw)
29.0		16.5		audi fox
26.0		15.5		volkswagen dasher
26.0		14.5		opel manta
31.0		16.5		toyota corona
32.0		19.0		datsun 710
28.0		14.5		dodge colt
24.0		15.5		fiat 128
26.0		14.0		fiat 124 tc
24.0		15.0		honda civic
26.0		15.5		subaru
31.0		16.0		fiat x1.9
19.0		16.0		plymouth valiant custom
18.0		16.0		chevrolet nova
15.0		21.0		mercury monarch
15.0		19.5		ford maverick
16.0		11.5		pontiac catalina
15.0		14.0		chevrolet bel air
16.0		14.5		plymouth grand fury
14.0		13.5		ford ltd
17.0		21.0		buick century
16.0		18.5		chevroelt chevelle malibu
15.0		19.0		amc matador
18.0		19.0		plymouth fury
21.0		15.0		buick skyhawk
20.0		13.5		chevrolet monza 2+2
13.0		12.0		ford mustang ii
29.0		16.0		toyota corolla
23.0		17.0		ford pinto
20.0		16.0		amc gremlin
23.0		18.5		pontiac astro
24.0		13.5		toyota corona
25.0		16.5		volkswagen dasher
24.0		17.0		datsun 710
18.0		14.5		ford pinto
29.0		14.0		volkswagen rabbit
19.0		17.0		amc pacer
23.0		15.0		audi 100ls
23.0		17.0		peugeot 504
22.0		14.5		volvo 244dl
25.0		13.5		saab 99le
33.0		17.5		honda civic cvcc
28.0		15.5		fiat 131
25.0		16.9		opel 1900
25.0		14.9		capri ii
26.0		17.7		dodge colt
27.0		15.3		renault 12tl
17.5		13.0		chevrolet chevelle malibu classic
16.0		13.0		dodge coronet brougham
15.5		13.9		amc matador
14.5		12.8		ford gran torino
22.0		15.4		plymouth valiant
22.0		14.5		chevrolet nova
24.0		17.6		ford maverick
22.5		17.6		amc hornet
29.0		22.2		chevrolet chevette
24.5		22.1		chevrolet woody
29.0		14.2		vw rabbit
33.0		17.4		honda civic
20.0		17.7		dodge aspen se
18.0		21.0		ford granada ghia
18.5		16.2		pontiac ventura sj
17.5		17.8		amc pacer d/l
29.5		12.2		volkswagen rabbit
32.0		17.0		datsun b-210
28.0		16.4		toyota corolla
26.5		13.6		ford pinto
20.0		15.7		volvo 245
13.0		13.2		plymouth volare premier v8
19.0		21.9		peugeot 504
19.0		15.5		toyota mark ii
16.5		16.7		mercedes-benz 280s
16.5		12.1		cadillac seville
13.0		12.0		chevy c10
13.0		15.0		ford f108
13.0		14.0		dodge d100
31.5		18.5		honda accord cvcc
30.0		14.8		buick opel isuzu deluxe
36.0		18.6		renault 5 gtl
25.5		15.5		plymouth arrow gs
33.5		16.8		datsun f-10 hatchback
17.5		12.5		chevrolet caprice classic
17.0		19.0		oldsmobile cutlass supreme
15.5		13.7		dodge monaco brougham
15.0		14.9		mercury cougar brougham
17.5		16.4		chevrolet concours
20.5		16.9		buick skylark
19.0		17.7		plymouth volare custom
18.5		19.0		ford granada
16.0		11.1		pontiac grand prix lj
15.5		11.4		chevrolet monte carlo landau
15.5		12.2		chrysler cordoba
16.0		14.5		ford thunderbird
29.0		14.5		volkswagen rabbit custom
24.5		16.0		pontiac sunbird coupe
26.0		18.2		toyota corolla liftback
25.5		15.8		ford mustang ii 2+2
30.5		17.0		chevrolet chevette
33.5		15.9		dodge colt m/m
30.0		16.4		subaru dl
30.5		14.1		volkswagen dasher
22.0		14.5		datsun 810
21.5		12.8		bmw 320i
21.5		13.5		mazda rx-4
43.1		21.5		volkswagen rabbit custom diesel
36.1		14.4		ford fiesta
32.8		19.4		mazda glc deluxe
39.4		18.6		datsun b210 gx
36.1		16.4		honda civic cvcc
19.9		15.5		oldsmobile cutlass salon brougham
19.4		13.2		dodge diplomat
20.2		12.8		mercury monarch ghia
19.2		19.2		pontiac phoenix lj
20.5		18.2		chevrolet malibu
20.2		15.8		ford fairmont (auto)
25.1		15.4		ford fairmont (man)
20.5		17.2		plymouth volare
19.4		17.2		amc concord
20.6		15.8		buick century special
20.8		16.7		mercury zephyr
18.6		18.7		dodge aspen
18.1		15.1		amc concord d/l
19.2		13.2		chevrolet monte carlo landau
17.7		13.4		buick regal sport coupe (turbo)
18.1		11.2		ford futura
17.5		13.7		dodge magnum xe
30.0		16.5		chevrolet chevette
27.5		14.2		toyota corona
27.2		14.7		datsun 510
30.9		14.5		dodge omni
21.1		14.8		toyota celica gt liftback
23.2		16.7		plymouth sapporo
23.8		17.6		oldsmobile starfire sx
23.9		14.9		datsun 200-sx
20.3		15.9		audi 5000
17.0		13.6		volvo 264gl
21.6		15.7		saab 99gle
16.2		15.8		peugeot 604sl
31.5		14.9		volkswagen scirocco
29.5		16.6		honda accord lx
21.5		15.4		pontiac lemans v6
19.8		18.2		mercury zephyr 6
22.3		17.3		ford fairmont 4
20.2		18.2		amc concord dl 6
20.6		16.6		dodge aspen 6
17.0		15.4		chevrolet caprice classic
17.6		13.4		ford ltd landau
16.5		13.2		mercury grand marquis
18.2		15.2		dodge st. regis
16.9		14.9		buick estate wagon (sw)
15.5		14.3		ford country squire (sw)
19.2		15.0		chevrolet malibu classic (sw)
18.5		13.0		chrysler lebaron town @ country (sw)
31.9		14.0		vw rabbit custom
34.1		15.2		maxda glc deluxe
35.7		14.4		dodge colt hatchback custom
27.4		15.0		amc spirit dl
25.4		20.1		mercedes benz 300d
23.0		17.4		cadillac eldorado
27.2		24.8		peugeot 504
23.9		22.2		oldsmobile cutlass salon brougham
34.2		13.2		plymouth horizon
34.5		14.9		plymouth horizon tc3
31.8		19.2		datsun 210
37.3		14.7		fiat strada custom
28.4		16.0		buick skylark limited
28.8		11.3		chevrolet citation
26.8		12.9		oldsmobile omega brougham
33.5		13.2		pontiac phoenix
41.5		14.7		vw rabbit
38.1		18.8		toyota corolla tercel
32.1		15.5		chevrolet chevette
37.2		16.4		datsun 310
28.0		16.5		chevrolet citation
26.4		18.1		ford fairmont
24.3		20.1		amc concord
19.1		18.7		dodge aspen
34.3		15.8		audi 4000
29.8		15.5		toyota corona liftback
31.3		17.5		mazda 626
37.0		15.0		datsun 510 hatchback
32.2		15.2		toyota corolla
46.6		17.9		mazda glc
27.9		14.4		dodge colt
40.8		19.2		datsun 210
44.3		21.7		vw rabbit c (diesel)
43.4		23.7		vw dasher (diesel)
36.4		19.9		audi 5000s (diesel)
30.0		21.8		mercedes-benz 240d
44.6		13.8		honda civic 1500 gl
33.8		18.0		subaru dl
29.8		15.3		vokswagen rabbit
32.7		11.4		datsun 280-zx
23.7		12.5		mazda rx-7 gs
35.0		15.1		triumph tr7 coupe
32.4		17.0		honda accord
27.2		15.7		plymouth reliant
26.6		16.4		buick skylark
25.8		14.4		dodge aries wagon (sw)
23.5		12.6		chevrolet citation
30.0		12.9		plymouth reliant
39.1		16.9		toyota starlet
39.0		16.4		plymouth champ
35.1		16.1		honda civic 1300
32.3		17.8		subaru
37.0		19.4		datsun 210 mpg
37.7		17.3		toyota tercel
34.1		16.0		mazda glc 4
34.7		14.9		plymouth horizon 4
34.4		16.2		ford escort 4w
29.9		20.7		ford escort 2h
33.0		14.2		volkswagen jetta
33.7		14.4		honda prelude
32.4		16.8		toyota corolla
32.9		14.8		datsun 200sx
31.6		18.3		mazda 626
28.1		20.4		peugeot 505s turbo diesel
30.7		19.6		volvo diesel
25.4		12.6		toyota cressida
24.2		13.8		datsun 810 maxima
22.4		15.8		buick century
26.6		19.0		oldsmobile cutlass ls
20.2		17.1		ford granada gl
17.6		16.6		chrysler lebaron salon
28.0		19.6		chevrolet cavalier
27.0		18.6		chevrolet cavalier wagon
34.0		18.0		chevrolet cavalier 2-door
31.0		16.2		pontiac j2000 se hatchback
29.0		16.0		dodge aries se
27.0		18.0		pontiac phoenix
24.0		16.4		ford fairmont futura
36.0		15.3		volkswagen rabbit l
37.0		18.2		mazda glc custom l
31.0		17.6		mazda glc custom
38.0		14.7		plymouth horizon miser
36.0		17.3		mercury lynx l
36.0		14.5		nissan stanza xe
36.0		14.5		honda accord
34.0		16.9		toyota corolla
38.0		15.0		honda civic
32.0		15.7		honda civic (auto)
38.0		16.2		datsun 310 gx
25.0		16.4		buick century limited
38.0		17.0		oldsmobile cutlass ciera (diesel)
26.0		14.5		chrysler lebaron medallion
22.0		14.7		ford granada l
32.0		13.9		toyota celica gt
36.0		13.0		dodge charger 2.2
27.0		17.3		chevrolet camaro
27.0		15.6		ford mustang gl
44.0		24.6		vw pickup
32.0		11.6		dodge rampage
28.0		18.6		ford ranger
31.0		19.4		chevy s-10

In [24]:
con.commit()
con.close()